export const burgerExtras = [
  { id: "extra-smashed-patty", name: "Extra Smashed Patty", price: 40 },
  { id: "bacon", name: "Bacon", price: 20 },
  { id: "cheese", name: "Cheese", price: 15 },
  { id: "ranch", name: "Ranch", price: 10 },
  { id: "mushroom", name: "Mushroom", price: 15 },
  { id: "caramelized-onion", name: "Caramelized Onion", price: 10 },
  { id: "jalapeno", name: "Jalapeño", price: 10 },
  { id: "tux-sauce", name: "TUX Sauce", price: 10 },
  { id: "extra-bun", name: "Extra Bun", price: 10 },
  { id: "pickle", name: "Pickle", price: 5 },
  { id: "condiments", name: "BBQ / Ketchup / Sweet Chili / Hot Sauce", price: 5 },
];

export const hawawshiExtras = [
  { id: "mozzarella-cheese", name: "Mozzarella Cheese", price: 20 },
  { id: "tux-hawawshi-sauce", name: "TUX Hawawshi Sauce", price: 10 },
  { id: "hawawshi-condiments", name: "BBQ / Ketchup / Sweet Chili / Hot Sauce", price: 5 },
];

export const menuData = [
  {
    id: "single-smashed-patty",
    name: "Single Smashed Patty",
    description: "Smashed patty, cheese, TUX sauce, pickles, tomato, onion, lettuce.",
    price: 95,
    category: "Smash Burgers",
    extras: burgerExtras,
  },
  {
    id: "double-smashed-patty",
    name: "Double Smashed Patty",
    description: "Two smashed patties, cheese, TUX sauce, pickles, tomato, onion, lettuce.",
    price: 140,
    category: "Smash Burgers",
    extras: burgerExtras,
  },
  {
    id: "triple-smashed-patty",
    name: "Triple Smashed Patty",
    description: "Triple the patties with all the classic TUX toppings and sauce.",
    price: 160,
    category: "Smash Burgers",
    extras: burgerExtras,
  },
  {
    id: "quatro-smashed-patty",
    name: "TUX Quatro Smashed Patty",
    description: "Four smashed patties, cheese, caramelized onion, mushroom, TUX sauce.",
    price: 190,
    category: "Smash Burgers",
    extras: burgerExtras,
  },
  {
    id: "tuxify-single",
    name: "TUXIFY Single",
    description: "Brioche bun, beef patty, American cheese, pickles, chopped onion, ketchup, TUXIFY sauce.",
    price: 120,
    category: "TUXIFY",
    extras: burgerExtras,
  },
  {
    id: "tuxify-double",
    name: "TUXIFY Double",
    description: "Double beef patties with American cheese, pickles, onion, ketchup, TUXIFY sauce.",
    price: 160,
    category: "TUXIFY",
    extras: burgerExtras,
  },
  {
    id: "tuxify-triple",
    name: "TUXIFY Triple",
    description: "Three beef patties layered with American cheese and TUXIFY sauce.",
    price: 200,
    category: "TUXIFY",
    extras: burgerExtras,
  },
  {
    id: "tuxify-quatro",
    name: "TUXIFY Quatro",
    description: "Four beef patties, American cheese, pickles, chopped onion, ketchup, TUXIFY sauce.",
    price: 240,
    category: "TUXIFY",
    extras: burgerExtras,
  },
  {
    id: "classic-fries-small",
    name: "Classic Fries (Small)",
    price: 25,
    category: "Fries",
    extras: [],
  },
  {
    id: "classic-fries-large",
    name: "Classic Fries (Large)",
    price: 30,
    category: "Fries",
    extras: [],
  },
  {
    id: "cheese-fries",
    name: "Cheese Fries",
    price: 30,
    category: "Fries",
    extras: [],
  },
  {
    id: "chili-fries",
    name: "Chili Fries",
    price: 40,
    category: "Fries",
    extras: [],
  },
  {
    id: "tux-fries",
    name: "TUX Fries",
    description: "Fries, smashed patty, cheese, pickles, caramelised onion, jalapeño, TUX sauce.",
    price: 75,
    category: "Fries",
    extras: [],
  },
  {
    id: "doppy-fries",
    name: "Doppy Fries",
    price: 95,
    category: "Fries",
    extras: [],
  },
  {
    id: "classic-hawawshi",
    name: "Classic Hawawshi",
    description: "Baladi bread, hawawshi meat, onion. Served with chili sauce.",
    price: 80,
    category: "Hawawshi",
    extras: hawawshiExtras,
  },
  {
    id: "tux-hawawshi",
    name: "TUX Hawawshi",
    description: "Baladi bread, hawawshi meat, mozzarella, onion, TUX hawawshi sauce.",
    price: 100,
    category: "Hawawshi",
    extras: hawawshiExtras,
  },
  {
    id: "extra-smashed-patty",
    name: "Extra Smashed Patty",
    price: 40,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "bacon",
    name: "Bacon",
    price: 20,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "cheese",
    name: "Cheese",
    price: 15,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "ranch",
    name: "Ranch",
    price: 10,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "mushroom",
    name: "Mushroom",
    price: 15,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "caramelized-onion",
    name: "Caramelized Onion",
    price: 10,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "jalapeno",
    name: "Jalapeño",
    price: 10,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "tux-sauce",
    name: "TUX Sauce",
    price: 10,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "extra-bun",
    name: "Extra Bun",
    price: 10,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "pickle",
    name: "Pickle",
    price: 5,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "condiments",
    name: "BBQ / Ketchup / Sweet Chili / Hot Sauce",
    price: 5,
    category: "Burger Extras",
    extras: [],
  },
  {
    id: "mozzarella-cheese",
    name: "Mozzarella Cheese",
    price: 20,
    category: "Hawawshi Extras",
    extras: [],
  },
  {
    id: "tux-hawawshi-sauce",
    name: "TUX Hawawshi Sauce",
    price: 10,
    category: "Hawawshi Extras",
    extras: [],
  },
  {
    id: "hawawshi-condiments",
    name: "BBQ / Ketchup / Sweet Chili / Hot Sauce",
    price: 5,
    category: "Hawawshi Extras",
    extras: [],
  },
  {
    id: "soda",
    name: "Soda",
    price: 20,
    category: "Drinks",
    extras: [],
  },
  {
    id: "water",
    name: "Water",
    price: 10,
    category: "Drinks",
    extras: [],
  },
];

export const menuIndex = new Map(menuData.map((item) => [item.id, item]));
